version: '3'
services:
  fastapi:
    build:
      context: ./fastapi
    container_name: example_server.fastapi
    volumes:
      - ./fastapi/app:/app
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"

  reactjs:
    build:
      context: ./reactjs
    container_name: example_server.reactjs
    volumes:
      - ./reactjs/app:/app
      - ./reactjs/app/node_modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"

networks:
  default:
    name: example_server
    driver: bridge
    attachable: true
