version: '3'
services:
  fastapi:
    build:
      context: ./fastapi
    container_name: example_server.fastapi
    volumes:
      - ./fastapi/app:/app
    environment:
      PORT: "8080"
    ports:
      - "8080:8080"

networks:
  default:
    name: example_server
    driver: bridge
    attachable: true
